Repository LutherNavigator/LutherNavigator, pull requests merged in 2021-04, with the labels that each got.

#155 Post images
  src/config.ts
  src/routes/image.ts
  src/routes/post.ts
  src/views/createPost.html
Labels: backend, enhancement

#156 Update list of devices for UI testing
  test/ui/mobile_emulation.ts
Labels: testing

#157 Minor change
  src/views/index.html
Labels: frontend

#158 Make three word location description optional
  src/routes/post.ts
  src/views/createPost.html
Labels: backend, enhancement, frontend

#159 Coverage Updates
  .github/workflows/test.yml
  .gitignore
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  jest.config.ts
  src/package-lock.json
Labels: backend, documentation, enhancement, frontend, testing

#160 Update docs [coverage]
  README.md
Labels: documentation

#161 Improve test coverage
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/services/util.ts
  test/services/util.test.ts
  test/services/verify.test.ts
Labels: bug, testing

#162 Disapproval reason
  .gitattributes
  src/emails/accountNotApproved.html
  src/emails/accountNotApproved.txt
  src/emails/postNotApproved.html
  src/emails/postNotApproved.txt
  src/routes/api.ts
  src/static/js/admin-posts.js
  src/static/js/admin-registration.js
  src/static/js/admin-status.js
  src/static/js/admin-suspension.js
  src/static/js/admin-variables.js
  src/views/admin-posts.html
  src/views/admin-registration.html
Labels: backend, feature, frontend

#163 Delete users and posts
  src/routes/api.ts
  src/services/user.ts
  src/static/js/admin-stats.js
  src/views/admin-stats.html
Labels: backend, feature, frontend

#165 Post user status
  src/dbinit.ts
  src/routes/post.ts
  src/services/post.ts
  test/services/post.test.ts
  test/services/userStatusChange.test.ts
Labels: backend, database, enhancement

#167 Admin favorites service
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/dbinit.ts
  src/services.ts
  src/services/adminFavorites.ts
  test/services/adminFavorites.test.ts
  test/services/userStatusChange.test.ts
Labels: backend, database, feature, testing

#168 Admin favorites
  src/routes/api.ts
  src/routes/index.ts
  src/services/admin.ts
  src/static/css/admin.css
  src/static/js/admin-stats.js
  src/views/admin-stats.html
  src/views/index.html
Labels: backend, feature, frontend

#171 Add the branch coverage statistics
  .gitignore
  README.md
  coverage/badge-branches.svg
Labels: feature, testing

#173 Improve branch coverage
  coverage/badge-branches.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/services/program.ts
  src/services/suspended.ts
  test/services/meta.test.ts
  test/services/passwordReset.test.ts
  test/services/post.test.ts
  test/services/query.test.ts
  test/services/session.test.ts
  test/services/suspended.test.ts
  test/services/user.test.ts
  test/services/userStatusChange.test.ts
  test/services/verify.test.ts
Labels: enhancement, testing

#180 Social links
  src/static/css/main.css
  src/views/layouts/default.html
Labels: enhancement, frontend

#179 Hide image name overflow on new post page
  src/static/css/createPost.css
Labels: bug, frontend

#176 CGL favorites page
  src/index.ts
  src/routes.ts
  src/routes/cglFavorites.ts
  src/services/post.ts
  src/views/cglFavorites.html
Labels: feature, frontend

#178 Service return types
  src/services/admin.ts
  src/services/image.ts
  src/services/locationType.ts
  src/services/meta.ts
  src/services/passwordReset.ts
  src/services/post.ts
  src/services/postImage.ts
  src/services/program.ts
  src/services/query.ts
  src/services/rating.ts
  src/services/session.ts
  src/services/suspended.ts
  src/services/user.ts
  src/services/userStatus.ts
  src/services/userStatusChange.ts
  src/services/util.ts
  src/services/verify.ts
  test/services/post.test.ts
  test/services/query.test.ts
  test/services/user.test.ts
  test/services/userStatusChange.test.ts
Labels: backend, bug, enhancement

#182 Improve admin heart change time
  src/static/js/admin-stats.js
Labels: enhancement, frontend

#177 Post vote service
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/dbinit.ts
  src/services.ts
  src/services/post.ts
  src/services/postVote.ts
  src/services/user.ts
  test/services/postVote.test.ts
Labels: backend, database, feature, testing

#183 Post upvote frontend
  coverage/badge-statements.svg
  src/routes/api.ts
  src/routes/post.ts
  src/services/postVote.ts
  src/static/css/main.css
  src/static/css/post.css
  src/static/js/post.js
  src/views/post.html
  test/services/postVote.test.ts
Labels: backend, feature, frontend

#184 Test fixes
  test/services/adminFavorites.test.ts
  test/services/image.test.ts
  test/services/locationType.test.ts
  test/services/passwordReset.test.ts
  test/services/post.test.ts
  test/services/postImage.test.ts
  test/services/postVote.test.ts
  test/services/rating.test.ts
  test/services/session.test.ts
  test/services/suspended.test.ts
  test/services/user.test.ts
  test/services/userStatus.test.ts
  test/services/userStatusChange.test.ts
  test/services/verify.test.ts
Labels: bug, testing

#185 Post city and country
  src/dbinit.ts
  src/routes/post.ts
  src/services/post.ts
  src/static/js/admin-posts.js
  src/views/admin-posts.html
  src/views/createPost.html
  src/views/post.html
  test/services/adminFavorites.test.ts
  test/services/post.test.ts
  test/services/postImage.test.ts
  test/services/postVote.test.ts
  test/services/query.test.ts
  test/services/userStatusChange.test.ts
Labels: backend, database, feature, frontend, testing

#188 City and country sort
  src/routes/post.ts
  src/routes/query.ts
  src/services/query.ts
  src/views/query.html
Labels: backend, bug, enhancement, frontend

#189 Marketing message popover
  src/routes/util.ts
  src/static/css/main.css
  src/static/js/main.js
  src/views/layouts/default.html
Labels: feature, frontend

#190 Featured programs
  src/routes/index.ts
  src/services/program.ts
  src/static/img/programs/adriatic.jpg
  src/static/img/programs/chicago.jpg
  src/static/img/programs/j-term.jpg
  src/static/img/programs/malta.jpg
  src/static/img/programs/münster.jpg
  src/static/img/programs/nottingham-summer.jpg
  src/static/img/programs/nottingham.jpg
  src/static/img/programs/other.jpg
  src/static/img/programs/rochester.jpg
  src/static/img/programs/washington.jpg
  src/views/index.html
  src/views/query.html
Labels: feature, frontend

#191 Fixes
  scripts/to_csv.py
  src/config.ts
Labels: bug, enhancement

#192 About, terms of use, privacy policy
  src/index.ts
  src/routes.ts
  src/routes/about.ts
  src/routes/terms.ts
  src/views/about.html
  src/views/layouts/default.html
  src/views/privacy.html
  src/views/register.html
  src/views/terms.html
  test/ui/mobile_emulation.ts
  test/ui/uitest.ts
Labels: feature, frontend

#194 Update about and terms of use
  src/views/about.html
  src/views/register.html
  src/views/terms.html
Labels: frontend

#195 Show no search results message
  src/views/query.html
Labels: enhancement, frontend

#201 Outdoor attraction location type
  src/dbinit.ts
  src/static/css/admin.css
  src/static/js/admin-stats.js
  test/services/locationType.test.ts
Labels: database, enhancement, frontend
