Repository LutherNavigator/LutherNavigator, pull requests merged in 2021-02, with the labels that each got.

#85 Update the intro per Jon's suggestion
  src/views/index.html
Labels: frontend

#86 Code Coverage
  .gitignore
  README.md
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  coverage/coverage-summary.json
  package-lock.json
  package.json
  scripts/test.py
  src/package-lock.json
Labels: testing

#87 Bump version number
  package.json
Labels: bug

#84 Admin page completion
  src/emails/accountApproved.html
  src/emails/accountApproved.txt
  src/emails/accountNotApproved.html
  src/emails/accountNotApproved.txt
  src/emails/postApproved.html
  src/emails/postApproved.txt
  src/emails/postNotApproved.html
  src/emails/postNotApproved.txt
  src/routes/admin.ts
  src/routes/api.ts
  src/static/css/admin.css
  src/static/css/main.css
  src/static/js/admin.js
  src/views/partials/admin.html
Labels: backend, feature

#89 Split and upgrade tests
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  coverage/coverage-summary.json
  jest.config.js
  jest.config.ts
  scripts/test.py
  src/db.ts
  src/dbinit.ts
  src/index.ts
  src/routes/api.ts
  src/routes/image.ts
  src/routes/index.ts
  src/routes/login.ts
  src/routes/logout.ts
  src/routes/passwordReset.ts
  src/routes/post.ts
  src/routes/profile.ts
  src/routes/register.ts
  src/routes/util.ts
  src/services.ts
  src/services/admin.ts
  src/services/image.ts
  src/services/locationType.ts
  src/services/meta.ts
  src/services/passwordReset.ts
  src/services/post.ts
  src/services/postImage.ts
  src/services/rating.ts
  src/services/session.ts
  src/services/user.ts
  src/services/userStatus.ts
  src/services/util.ts
  src/services/verify.ts
  test/services.test.ts
  test/services/email.test.ts
  test/services/image.test.ts
  test/services/locationType.test.ts
  test/services/meta.test.ts
  test/services/passwordReset.test.ts
  test/services/post.test.ts
  test/services/postImage.test.ts
  test/services/rating.test.ts
  test/services/session.test.ts
  test/services/setup.ts
  test/services/user.test.ts
  test/services/userStatus.test.ts
  test/services/util.test.ts
  test/services/util.ts
  test/services/verify.test.ts
  test/ui/uitest.ts
Labels: backend, testing

#91 Device Emulation
  jest.config.ts
  scripts/env.py
  scripts/test.py
  scripts/to_csv.py
  test/ui/mobile_emulation.ts
  test/ui/uitest.ts
Labels: frontend, testing

#93 Testing and coverage
  .gitignore
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  coverage/coverage-summary.json
Labels: backend, testing

#97 Query logic and tests
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/services.ts
  src/services/postImage.ts
  src/services/query.ts
  test/services/query.test.ts
  test/services/util.ts
Labels: backend, testing

#98 Admin control panel programs tab
  coverage/badge-branches.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/dbinit.ts
  src/routes/admin.ts
  src/routes/api.ts
  src/services/program.ts
  src/static/css/admin.css
  src/static/js/admin.js
  src/views/admin-programs.html
  test/services/program.test.ts
  test/ui/mobile_emulation.ts
  test/ui/uitest.ts
Labels: backend, testing
