Repository LutherNavigator/LutherNavigator, pull requests merged in 2021-03, with the labels that each got.

#99 Update the LICENSE and add it to the README
  LICENSE
  README.md
Labels: documentation

#103 Query page (1)
  src/routes/query.ts
  src/static/css/index.css
  src/static/css/post.css
  src/static/css/query.css
  src/views/index.html
  src/views/query.html
Labels: backend

#104 Query page (2)
  src/routes/query.ts
  src/services/query.ts
  src/static/js/index.js
  src/static/js/query.js
  src/views/index.html
  src/views/query.html
  test/services/query.test.ts
Labels: backend, database

#105 Post user fix
  src/routes/post.ts
  src/services/query.ts
  src/views/500.html
Labels: bug

#106 Handle missing post
  src/routes/post.ts
Labels: backend, bug

#107 Fix admin page width
  src/static/css/admin.css
Labels: bug, frontend

#108 Stretched images
  src/static/css/post.css
  src/static/css/profile.css
  src/views/post.html
  src/views/profile.html
Labels: enhancement, frontend

#109 User status change
  src/dbinit.ts
  src/routes/profile.ts
  src/services.ts
  src/services/userStatusChange.ts
  src/views/profile.html
Labels: backend, database, feature, frontend

#110 Post deletion
  src/routes/post.ts
  src/views/post.html
Labels: backend, feature, frontend

#112 Location rating (1)
  src/helpers.ts
  src/routes/post.ts
  src/routes/util.ts
  src/static/css/createPost.css
  src/static/css/main.css
  src/static/css/post.css
  src/static/js/createPost.js
  src/views/createPost.html
  src/views/post.html
Labels: feature, frontend

#111 User status change (2)
  coverage/badge-branches.svg
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/routes/admin.ts
  src/routes/api.ts
  src/services/userStatusChange.ts
  src/static/css/admin.css
  src/static/js/admin.js
  src/views/admin-status.html
  test/services/userStatusChange.test.ts
Labels: backend, feature, frontend, testing

#113 Location rating (2)
  src/routes/post.ts
  src/views/createPost.html
Labels: backend, feature, frontend

#117 Argparse
  README.md
  run.bat
  run.sh
  script.bat
  script.sh
  scripts/admin.py
  scripts/test.py
Labels: backend, documentation, frontend, testing

#119 UI testing and a few changes to testing automation scripts
  scripts/admin.py
  scripts/test.py
  test/ui/mobile_emulation.ts
  test/ui/uitest.ts
Labels: documentation, testing

#120 Remove branch coverage
  .gitignore
  README.md
  coverage/badge-branches.svg
Labels: documentation, testing

#121 Front end fixes
  src/static/css/index.css
  src/static/css/post.css
  src/views/404.html
  src/views/post.html
  src/views/query.html
Labels: bug, frontend

#122 Account suspension (1)
  src/dbinit.ts
  src/services.ts
  src/services/suspended.ts
  src/services/util.ts
Labels: backend, database, feature

#124 Profile program fix
  src/services/post.ts
Labels: backend, bug

#123 Post details
  src/dbinit.ts
  src/routes/post.ts
  src/services/post.ts
  src/views/createPost.html
  src/views/post.html
Labels: backend, database, feature, frontend

#128 Account suspension (2)
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/routes/login.ts
  src/services/suspended.ts
  src/services/user.ts
  test/services/suspended.test.ts
  test/services/user.test.ts
Labels: enhancement, testing

#130 Allow for running specific tests
  package-lock.json
  scripts/admin.py
  scripts/test.py
  src/package-lock.json
Labels: enhancement, feature, testing

#131 Account suspension (3)
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/routes/admin.ts
  src/routes/api.ts
  src/services/suspended.ts
  src/services/util.ts
  src/static/css/admin.css
  src/static/js/admin-suspension.js
  src/views/admin-suspension.html
Labels: backend, feature, frontend

#129 UI
  package-lock.json
  package.json
  src/static/css/index.css
  src/static/css/main.css
  src/static/css/post.css
  src/static/css/profile.css
  src/static/css/query.css
  src/views/admin-posts.html
  src/views/admin-programs.html
  src/views/admin-registration.html
  src/views/admin-stats.html
  src/views/admin-status.html
  src/views/admin-variables.html
  src/views/index.html
  src/views/layouts/default.html
  src/views/post.html
  src/views/profile.html
  src/views/query.html
Labels: frontend

#133 Admin user and post statistics
  coverage/badge-functions.svg
  coverage/badge-lines.svg
  coverage/badge-statements.svg
  src/routes/api.ts
  src/services/admin.ts
  src/static/css/admin.css
  src/static/js/admin-stats.js
  src/static/js/admin.js
  src/views/admin-stats.html
  test/services/admin.test.ts
Labels: feature, frontend

#138 Only return verified accounts from getUnapproved
  src/services/user.ts
  test/services/user.test.ts
Labels: backend, bug

#139 GitHub Actions
  .github/workflows/test.yml
Labels: backend, enhancement, feature, frontend, testing

#140 Fix exit code
  .github/workflows/test.yml
  README.md
  scripts/test.py
Labels: enhancement, testing

#141 Update README and scripts
  README.md
  scripts/admin.py
  scripts/db.py
  scripts/env.py
  scripts/test.py
  scripts/to_csv.py
Labels: documentation, enhancement, testing

#142 Bot Automation
  .github/workflows/test.yml
  README.md
  package.json
Labels: documentation, enhancement, feature, testing

#144 Exit Code Fix
  .github/workflows/test.yml
  package-lock.json
Labels: bug

#146 Update the Branch
  .github/workflows/test.yml
Labels: bug

#150 Fix post test unapproved count
  test/services/post.test.ts
Labels: bug, testing

#149 Decode URI on post search
  src/static/js/query.js
Labels: bug, frontend

#148 Refill invalid registration form
  src/routes/register.ts
  src/views/register.html
Labels: backend, bug, frontend

#151 Resize post images if they are too large
  src/package-lock.json
  src/package.json
  src/routes/post.ts
Labels: backend, enhancement
