Repository LutherNavigator/LutherNavigator, pull requests merged in 2021-01, with the labels that each got.

#53 Registration page
  src/index.ts
  src/routes.ts
  src/routes/register.ts
  src/static/css/login.css
  src/static/css/main.css
  src/views/login.html
  src/views/register.html
Labels: frontend

#54 Password reset view and routing logic
  src/emailer.ts
  src/emails/passwordReset.html
  src/emails/passwordReset.txt
  src/index.ts
  src/routes.ts
  src/routes/passwordReset.ts
  src/routes/util.ts
  src/services.ts
  src/static/css/main.css
  src/views/login.html
  src/views/passwordReset.html
  src/views/passwordResetRequest.html
  src/views/passwordResetRequestSuccess.html
  src/views/passwordResetSuccess.html
  src/views/profile.html
Labels: backend, feature, frontend

#68 Post image routing/view
  src/routes/image.ts
  src/routes/post.ts
  src/views/post.html
Labels: backend, frontend

#70 New post page
  src/routes/post.ts
  src/static/css/createPost.css
  src/static/css/main.css
  src/static/js/createPost.js
  src/static/js/profile.js
  src/views/createPost.html
  src/views/layouts/default.html
Labels: frontend

#76 Post login fix
  src/routes/post.ts
  src/static/css/post.css
Labels: bug

#77 Beginning of the admin pages
  src/helpers.ts
  src/index.ts
  src/routes.ts
  src/routes/admin.ts
  src/routes/api.ts
  src/services.ts
  src/services/admin.ts
  src/static/css/admin.css
  src/static/css/main.css
  src/static/js/admin.js
  src/views/admin-posts.html
  src/views/admin-registration.html
  src/views/admin-stats.html
  src/views/admin-variables.html
  src/views/layouts/default.html
  src/views/partials/admin.html
Labels: backend

#78 Admin page
  src/config.ts
  src/dbinit.ts
  src/routes/api.ts
  src/routes/login.ts
  src/routes/post.ts
  src/routes/util.ts
  src/services/post.ts
  src/services/user.ts
  src/services/util.ts
  src/static/css/main.css
  src/static/js/admin.js
  src/views/partials/admin.html
  src/views/passwordReset.html
  src/views/passwordResetRequest.html
  src/views/passwordResetRequestSuccess.html
  src/views/registerSuccess.html
  src/views/registerVerify.html
  test/services.test.ts
Labels: backend, feature

#81 Post approval
  src/routes/api.ts
  src/services/post.ts
  src/static/js/admin.js
  src/views/admin-posts.html
  src/views/admin-registration.html
  test/services.test.ts
Labels: backend, enhancement, feature, testing
